version: '3.4'
services: 
  worker:
    build: .
    image: &img worker 
    command: [celery, worker, --app=worker.app]
    environment: &env      
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app 

  runner:
    build: .
    image: *img
    command: [python, runner.py]
    environment: *env
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app

  rabbitmq:
    image: rabbitmq:3.8